name: AutoBuild .NET

on: [push, pull_request]

jobs:
  BuildLiunx:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build
        run: dotnet build CDJ/CDJ.csproj --configuration Release --output ./CDJ/Release
        
      - name: Del
        run: rm -rf ./CDJ/Release//CDJ.pdb ./CDJ/Release//CDJ.deps.json ./CDJ/Release//CDJ.runtimeconfig.json ./CDJ/Release//global.json

      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: CDJ-Linux
          path: ./CDJ/Release/
          
  BuildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build
        run: dotnet build CDJ/CDJ.csproj --configuration Release --output ./CDJ/Release
        
      - name: Del pdb
        run: del ./CDJ/Release/CDJ.pdb
      
      - name: Del deps
        run: del ./CDJ/Release/CDJ.deps.json
        
      - name: Del runtimeconfig
        run: del ./CDJ/Release/CDJ.runtimeconfig.json
      
      - name: Del global
        run: del ./CDJ/Release/global.json
        
      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: CDJ-Windows
          path: ./CDJ/Release/
      
      - name: BuildTestCDJ
        run: dotnet build TestCDJ/TestCDJ.csproj --configuration Release --output TestCDJ/Release
        
      - name: Del pdb
        run: del ./TestCDJ/Release/CDJ.pdb

      - name: Del deps
        run: del ./TestCDJ/Release/CDJ.deps.json

      - name: Del runtimeconfig
        run: del ./TestCDJ/Release/CDJ.runtimeconfig.json

      - name: Upload TestCDJ
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TestCDJ
          path: ./TestCDJ/Release